#!/usr/bin/env python3
"""CHI-style 6x7 mesh -- V2: 4 channels as 4 subnets, decoupled from read/write types.

Requires the `class_subnet` patch (subnet chosen per traffic class). Each CHI
channel is one open-loop (use_read_write=0) traffic class mapped to its own
subnet via class_subnet. Because the subnet is no longer tied to the 4 built-in
message types, we can also model WRITE coherence: write data is an extra class
that rides the DAT subnet in the RN->HN direction (CHI's DAT channel is
bidirectional). This is impossible in V1 (gen_chi_mesh.py), which had to spend
all 4 message types on the 4 channels.

Classes / channels (open-loop, rate-ratio approximation of causal coupling):
  c0 REQ     -> subnet 0, dest=HN, 1 flit   (read+write requests, RN->HN)
  c1 DAT(rd) -> subnet 1, dest=RN, 5 flit   (read data, HN->RN)
  c2 SNP     -> subnet 2, dest=RN, 1 flit   (snoops, ->RN)
  c3 RSP     -> subnet 3, dest=HN, 1 flit   (responses/Comp, ->HN)
  c4 DAT(wr) -> subnet 1, dest=HN, 5 flit   (write data, RN->HN; shares DAT net)

Tunables (env override): CHI_INJ, CHI_SNOOP, CHI_WFRAC, CHI_VCS.
Writes mesh6x7_chi_v2_anynet (topology) and mesh6x7_chi_v2 (config).
V1 files are left untouched.
"""
import os

ROWS, COLS = 6, 7
RN_PER, HN_PER = 2, 2
PER = RN_PER + HN_PER
INJ   = float(os.environ.get("CHI_INJ", 0.001))   # base request rate / node
                                                  # (DAT subnet carries both data
                                                  #  flows, so it saturates early)
SNOOP = float(os.environ.get("CHI_SNOOP", 1.0))   # SNP per REQ
WFRAC = float(os.environ.get("CHI_WFRAC", 0.3))   # fraction of requests that are writes
NUM_VCS = int(os.environ.get("CHI_VCS", 2))

here = os.path.dirname(os.path.abspath(__file__))

def rid(r, c):
    return r * COLS + c

n_routers = ROWS * COLS
rn_nodes, hn_nodes = [], []
for r in range(n_routers):
    base = PER * r
    rn_nodes += [base + 0, base + 1]
    hn_nodes += [base + 2, base + 3]

# ---- topology (identical structure to V1, self-contained file) ----
lines = []
for r in range(ROWS):
    for c in range(COLS):
        i = rid(r, c)
        base = PER * i
        parts = [f"router {i}"] + [f"node {base + k}" for k in range(PER)]
        if c + 1 < COLS:
            parts.append(f"router {rid(r, c+1)}")
        if r + 1 < ROWS:
            parts.append(f"router {rid(r+1, c)}")
        lines.append(" ".join(parts))
topo_path = os.path.join(here, "mesh6x7_chi_v2_anynet")
with open(topo_path, "w") as f:
    f.write("\n".join(lines) + "\n")

# ---- rates (open-loop, tied to request rate to mimic causality) ----
r = INJ
r_req    = round(r, 6)
r_dat_rd = round(r * (1 - WFRAC), 6)
r_snp    = round(r * SNOOP, 6)
r_rsp    = round(r * SNOOP + r * WFRAC, 6)   # snoop responses + write completions
r_dat_wr = round(r * WFRAC, 6)

hn_list = "{" + ",".join(map(str, hn_nodes)) + "}"
rn_list = "{" + ",".join(map(str, rn_nodes)) + "}"
vmax = NUM_VCS - 1

cfg = f"""// CHI-style 6x7 mesh -- V2: 4 channels = 4 subnets via class_subnet patch.
// Auto-generated by gen_chi_mesh_v2.py. Requires the class_subnet source patch.
// {n_routers} routers x {PER} terminals = {n_routers*PER} nodes (2 RN + 2 HN each).
//
// channel/class -> subnet (open-loop, use_read_write=0):
//   c0 REQ ->0  c1 DAT(rd)->1  c2 SNP ->2  c3 RSP ->3  c4 DAT(wr)->1 (shares DAT)

topology     = anynet;
network_file = mesh6x7_chi_v2_anynet;
routing_function = min;

// 5 classes carry the 4 channels (DAT split into read-data + write-data flows)
classes = 5;
use_read_write = {{0,0,0,0,0}};      // open-loop one-way flows, no auto reply

// each class maps directly to a subnet, independent of read/write semantics
subnets      = 4;
class_subnet = {{0,1,2,3,1}};        // REQ DAT_rd SNP RSP DAT_wr

// per-channel packet sizes (16B/flit, 64B line = 5 flit)
packet_size  = {{1,5,1,1,5}};        // REQ DAT_rd SNP RSP DAT_wr

// per-channel destinations (source = all nodes; dest set approximates direction)
traffic = {{hotspot({hn_list}),hotspot({rn_list}),hotspot({rn_list}),hotspot({hn_list}),hotspot({hn_list})}};

// rate-ratio model: snoop_factor={SNOOP}, write_fraction={WFRAC}, base req={INJ}
//   DAT_rd = req*(1-wf) ; DAT_wr = req*wf ; SNP = req*snoop ; RSP = req*snoop + req*wf
injection_rate = {{{r_req},{r_dat_rd},{r_snp},{r_rsp},{r_dat_wr}}};

num_vcs     = {NUM_VCS};
vc_buf_size = 8;
vc_allocator = islip;
sw_allocator = islip;
alloc_iters  = 1;

sim_type       = latency;
sample_period  = 1000;
warmup_periods = 3;
sim_count      = 1;
"""
cfg_path = os.path.join(here, "mesh6x7_chi_v2")
with open(cfg_path, "w") as f:
    f.write(cfg)

print(f"Wrote {topo_path} ({len(lines)} routers, {n_routers*PER} nodes)")
print(f"Wrote {cfg_path}")
print(f"  rates: REQ={r_req} DAT_rd={r_dat_rd} SNP={r_snp} RSP={r_rsp} DAT_wr={r_dat_wr}")
print(f"  (snoop_factor={SNOOP}, write_fraction={WFRAC})")
