#!/usr/bin/env python3
"""Generate a CHI-style coherence-traffic model on a 6x7 mesh for BookSim,
with CHI's 4 channels mapped to 4 INDEPENDENT PHYSICAL networks (subnets=4).

Topology:
- 6x7 mesh, each router hosts 4 terminals: 2 RN (cores) + 2 HN (home/dir).
  router r -> nodes 4r,4r+1 (RN) and 4r+2,4r+3 (HN). 168 nodes total.

CHI channels -> BookSim message types -> subnets (each subnet = 1 physical net):
    REQ = read_request  -> subnet 0   (RN -> HN)
    DAT = read_reply    -> subnet 1   (HN -> RN, the reply to REQ)
    SNP = write_request -> subnet 2   (-> RN)
    RSP = write_reply   -> subnet 3   (reply to SNP)

Two traffic classes carry the two request/reply pairs without colliding:
    class 0: write_fraction=0  -> only REQ/DAT ; traffic = hotspot(HN set)
    class 1: write_fraction=1  -> only SNP/RSP ; traffic = hotspot(RN set)

snoop amplification factor = class1_rate / class0_rate (default 1.0, tunable).

Writes: mesh6x7_chi_anynet (topology) and mesh6x7_chi (config).

NOTE (approximation): BookSim injects from every node at the same per-class
rate (no per-role gating). Because every router hosts both RN and HN, source/
destination *routers* are still the full set, so network-level latency/throughput
is a reasonable proxy. Snoop-with-data is modeled as a 1-flit RSP (no DAT return).
"""
import os

ROWS, COLS = 6, 7
RN_PER, HN_PER = 2, 2
PER = RN_PER + HN_PER  # terminals per router
# Defaults; can be overridden via env vars CHI_SNOOP / CHI_INJ / CHI_VCS (used by sweep).
SNOOP_FACTOR = float(os.environ.get("CHI_SNOOP", 1.0))  # class1 (SNP) rate vs class0 (REQ)
INJ = float(os.environ.get("CHI_INJ", 0.01))            # per-node, per-class request inj rate
NUM_VCS = int(os.environ.get("CHI_VCS", 2))             # VCs per subnet

here = os.path.dirname(os.path.abspath(__file__))

def rid(r, c):
    return r * COLS + c

n_routers = ROWS * COLS
rn_nodes, hn_nodes = [], []
for r in range(n_routers):
    base = PER * r
    rn_nodes += [base + 0, base + 1]
    hn_nodes += [base + 2, base + 3]

# ---- topology file ----
lines = []
for r in range(ROWS):
    for c in range(COLS):
        i = rid(r, c)
        base = PER * i
        parts = [f"router {i}"]
        for k in range(PER):
            parts.append(f"node {base + k}")
        if c + 1 < COLS:
            parts.append(f"router {rid(r, c+1)}")
        if r + 1 < ROWS:
            parts.append(f"router {rid(r+1, c)}")
        lines.append(" ".join(parts))
topo_path = os.path.join(here, "mesh6x7_chi_anynet")
with open(topo_path, "w") as f:
    f.write("\n".join(lines) + "\n")

# ---- config file ----
hn_list = "{" + ",".join(map(str, hn_nodes)) + "}"
rn_list = "{" + ",".join(map(str, rn_nodes)) + "}"
req_rate = INJ
snp_rate = round(INJ * SNOOP_FACTOR, 6)
vmax = NUM_VCS - 1

cfg = f"""// CHI-style traffic on a 6x7 mesh -- 4 INDEPENDENT PHYSICAL CHANNELS (subnets=4).
// Auto-generated by gen_chi_mesh.py.
// {n_routers} routers x {PER} terminals = {n_routers*PER} nodes
//   router r -> nodes {{{PER}r .. {PER}r+{PER-1}}}: first {RN_PER} = RN (cores), last {HN_PER} = HN (home/dir)
//
// CHI channel -> message type -> subnet (each subnet is a separate physical net):
//   REQ=read_request->subnet0  DAT=read_reply->subnet1
//   SNP=write_request->subnet2 RSP=write_reply->subnet3

topology     = anynet;
network_file = mesh6x7_chi_anynet;
routing_function = min;

// --- two classes carry the two req/reply pairs without type collision ---
classes = 2;
use_read_write = {{1,1}};
write_fraction = {{0,1}};   // class0 -> REQ/DAT only ; class1 -> SNP/RSP only

// snoop amplification factor = class1_rate / class0_rate = {SNOOP_FACTOR}
// (tune by editing the second value, or regenerate with a different SNOOP_FACTOR)
injection_rate = {{{req_rate},{snp_rate}}};

// destinations: REQ -> uniform over all HNs ; SNP -> uniform over all RNs
traffic = {{hotspot({{{hn_list}}}),hotspot({{{rn_list}}})}};

// packet sizes (16B/flit, 64B cache line = 5 flit)
read_request_size  = {{1,1}};   // REQ = 1 flit (control)
read_reply_size    = {{5,1}};   // DAT = 5 flit (cache line)
write_request_size = {{1,1}};   // SNP = 1 flit (control)
write_reply_size   = {{1,1}};   // RSP = 1 flit (control)

// --- 4 independent physical channels: one message type per subnet ---
subnets = 4;
read_request_subnet  = 0;   // REQ
read_reply_subnet    = 1;   // DAT
write_request_subnet = 2;   // SNP
write_reply_subnet   = 3;   // RSP

// each subnet carries a single channel, so each type spans the full VC range
read_request_begin_vc  = 0;  read_request_end_vc  = {vmax};
read_reply_begin_vc    = 0;  read_reply_end_vc    = {vmax};
write_request_begin_vc = 0;  write_request_end_vc = {vmax};
write_reply_begin_vc   = 0;  write_reply_end_vc   = {vmax};

num_vcs     = {NUM_VCS};
vc_buf_size = 8;
vc_allocator = islip;
sw_allocator = islip;
alloc_iters  = 1;

sim_type       = latency;
packet_size    = 1;          // overridden by *_size in read_write mode
sample_period  = 1000;
warmup_periods = 3;
sim_count      = 1;
"""
cfg_path = os.path.join(here, "mesh6x7_chi")
with open(cfg_path, "w") as f:
    f.write(cfg)

print(f"Wrote {topo_path} ({len(lines)} routers, {n_routers*PER} nodes)")
print(f"Wrote {cfg_path}  (subnets=4, RN={len(rn_nodes)}, HN={len(hn_nodes)}, snoop_factor={SNOOP_FACTOR})")
