#!/usr/bin/env python3
"""Generate a custom REQ-only BookSim config on the 7x6 CHI mesh.

Traffic:
  - Channel: REQ only (subnet 0), 1-flit packets
  - Sources: selected RNs on R4/R5 (2 each) and R13–R16 (1 each)
  - Destinations: selected HNs on R3/R5 (1), R4 (2), R13–R16 / R25–R28 / R37–R40 (1 each)
  - Per-source injection_rate = 0.2 (override with CHI_LAMBDA / CUSTOM_INJ)

Topology defaults match ZCN-LP (7x6 + 4 side SNs); link_latency defaults to 1.
"""
import os

ROWS = int(os.environ.get("CHI_ROWS", 7))
COLS = int(os.environ.get("CHI_COLS", 6))
RN_PER, HN_PER = 2, 2
PER = RN_PER + HN_PER

# Default SN placement (same as ZCN-LP); unused by this REQ-only mix but kept
# so the anynet file stays consistent with the rest of the project.
def _parse_sn_coords(s):
    if not s:
        return None
    out = []
    for part in s.replace(" ", "").split(";"):
        if not part:
            continue
        r, c = part.split(",")
        out.append((int(r), int(c)))
    return out

_sn_env = _parse_sn_coords(os.environ.get("CHI_SN_COORDS", ""))
SN_ROUTER_COORDS = _sn_env if _sn_env else [(3, 0), (4, 0), (3, 5), (4, 5)]

NUM_VCS = int(os.environ.get("CHI_VCS", 2))
VC_BUF_SIZE = int(os.environ.get("CHI_VC_BUF_SIZE", 4))
SW_ALLOCATOR = os.environ.get("CHI_SW_ALLOCATOR", "separable_output_first(round_robin)")
VC_ALLOCATOR = os.environ.get("CHI_VC_ALLOCATOR", "islip")
ROUTING = os.environ.get("CHI_ROUTING", "xy")
LINK_LAT = int(os.environ.get("CHI_LINK_LATENCY", 1))
LATENCY_THRES = repr(float(os.environ.get("CHI_LATENCY_THRES", 500.0)))
MAX_SAMPLES = int(os.environ.get("CHI_MAX_SAMPLES", 50))
STATS_OUT = os.environ.get("CHI_STATS_OUT", "req_custom_stats.m")
INJ = float(os.environ.get("CUSTOM_INJ", os.environ.get("CHI_LAMBDA", 0.2)))

# Router -> how many of its RNs are sources (take first N RNs: base+0..)
SRC_RN_COUNT = {
    4: 2, 5: 2,
    13: 1, 14: 1, 15: 1, 16: 1,
}
# Router -> how many of its HNs are destinations (take first N HNs: base+2..)
DST_HN_COUNT = {
    3: 1, 5: 1,
    4: 2,
    13: 1, 14: 1, 15: 1, 16: 1,
    25: 1, 26: 1, 27: 1, 28: 1,
    37: 1, 38: 1, 39: 1, 40: 1,
}

here = os.path.dirname(os.path.abspath(__file__))


def rid(r, c):
    return r * COLS + c


def router_nodes(router):
    base = PER * router
    return {
        "rn": [base + k for k in range(RN_PER)],
        "hn": [base + RN_PER + k for k in range(HN_PER)],
    }


n_routers = ROWS * COLS
sn_routers = [rid(r, c) for r, c in SN_ROUTER_COORDS]
sn_base = n_routers * PER
sn_nodes = [sn_base + i for i in range(len(sn_routers))]
total_nodes = n_routers * PER + len(sn_nodes)

src_nodes = []
for router, n in sorted(SRC_RN_COUNT.items()):
    if router >= n_routers:
        raise SystemExit(f"SRC router R{router} out of range for {ROWS}x{COLS}")
    src_nodes.extend(router_nodes(router)["rn"][:n])

dst_nodes = []
for router, n in sorted(DST_HN_COUNT.items()):
    if router >= n_routers:
        raise SystemExit(f"DST router R{router} out of range for {ROWS}x{COLS}")
    dst_nodes.extend(router_nodes(router)["hn"][:n])

# ---- topology (same mesh style as gen_chi_traffic) ----
topo_lines = []
for r in range(ROWS):
    for c in range(COLS):
        i = rid(r, c)
        base = PER * i
        parts = [f"router {i}"] + [f"node {base + k}" for k in range(PER)]
        if i in sn_routers:
            parts.append(f"node {sn_nodes[sn_routers.index(i)]}")
        for nb in (
            rid(r, c + 1) if c + 1 < COLS else None,
            rid(r, c - 1) if c - 1 >= 0 else None,
            rid(r + 1, c) if r + 1 < ROWS else None,
            rid(r - 1, c) if r - 1 >= 0 else None,
        ):
            if nb is not None:
                parts.append(f"router {nb} {LINK_LAT}")
        topo_lines.append(" ".join(parts))

topo_path = os.path.join(here, "chi_traffic_anynet")
with open(topo_path, "w") as f:
    f.write("\n".join(topo_lines) + "\n")

src_list = ",".join(map(str, src_nodes))
dst_list = ",".join(map(str, dst_nodes))
sn_comment = ", ".join(
    f"R{router}=node{sn_nodes[idx]}@({SN_ROUTER_COORDS[idx][0]},{SN_ROUTER_COORDS[idx][1]})"
    for idx, router in enumerate(sn_routers)
)

cfg = f"""// Custom REQ-only traffic (auto-generated by gen_req_custom_traffic.py).
// {n_routers} routers x {PER} RN/HN + {len(sn_nodes)} SN = {total_nodes} nodes.
// Topology: {ROWS}x{COLS}, SN placement: {sn_comment}.
// Mix: single class, REQ subnet only, packet_size=1.
// Sources ({len(src_nodes)} RNs): {src_list}
//   R4/R5: 2 RN each; R13–R16: 1 RN each (first N RNs per router).
// Destinations ({len(dst_nodes)} HNs): {dst_list}
//   R3/R5: 1 HN; R4: 2 HN; R13–16/R25–28/R37–40: 1 HN each (first N HNs).
// Per-source injection_rate = {INJ}; link_latency = {LINK_LAT}; routing = {ROUTING}.

topology     = anynet;
network_file = chi_traffic_anynet;
routing_function = {ROUTING};
anynet_cols  = {COLS};

classes        = 1;
use_read_write = {{0}};
subnets        = 4;
class_subnet   = {{0}};   // REQ only
class_source   = {{{{{src_list}}}}};
packet_size    = {{1}};
injection_rate = {{{INJ}}};
traffic        = {{hotspot({{{{{dst_list}}}}})}};

num_vcs     = {NUM_VCS};
vc_buf_size = {VC_BUF_SIZE};
vc_allocator = {VC_ALLOCATOR};
sw_allocator = {SW_ALLOCATOR};
alloc_iters  = 1;

sim_type       = latency;
sample_period  = 1000;
warmup_periods = 3;
sim_count      = 1;
max_samples    = {MAX_SAMPLES};
latency_thres  = {LATENCY_THRES};
"""
if STATS_OUT:
    cfg += f"stats_out = {STATS_OUT};\n"

cfg_path = os.path.join(here, "chi_traffic")
with open(cfg_path, "w") as f:
    f.write(cfg)

print(f"Wrote {topo_path} ({len(topo_lines)} routers, {total_nodes} nodes)")
print(f"Wrote {cfg_path}")
print(f"  link_latency={LINK_LAT} routing={ROUTING} vc_buf={VC_BUF_SIZE}")
print(f"  injection_rate={INJ} (per source RN)")
print(f"  SRC RNs ({len(src_nodes)}): {src_nodes}")
print(f"  DST HNs ({len(dst_nodes)}): {dst_nodes}")
