#!/usr/bin/env python3
"""Generate a subnet/channel-level CHI traffic report from BookSim output.

Inputs:
  ../runfiles/chi_traffic_summary.txt  - generated by gen_chi_traffic.py
  ../runfiles/chi_traffic.log          - generated by ../src/booksim chi_traffic

Outputs:
  v5_chi_subnet_summary.csv
  v5_chi_subnet_report.pdf
  v5_chi_subnet_report_p1.png
"""
import csv
import math
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RUNFILES = os.path.join(ROOT, "runfiles")
SUMMARY = os.path.join(RUNFILES, "chi_traffic_summary.txt")
LOG = os.path.join(RUNFILES, "chi_traffic.log")
CSV_OUT = os.path.join(HERE, "v5_chi_subnet_summary.csv")
PDF_OUT = os.path.join(HERE, "v5_chi_subnet_report.pdf")
PNG_OUT = os.path.join(HERE, "v5_chi_subnet_report_p1.png")

os.environ.setdefault("MPLCONFIGDIR", os.path.join(HERE, ".mplcache"))
os.makedirs(os.environ["MPLCONFIGDIR"], exist_ok=True)

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

CHANNELS = ["REQ", "RSP", "SNP", "DAT"]
SUBNET = {"REQ": 0, "RSP": 1, "SNP": 2, "DAT": 3}
COLORS = {"REQ": "#2563eb", "RSP": "#7c3aed", "SNP": "#16a34a", "DAT": "#dc2626"}


def _num(text):
    if text is None:
        return None
    if text.lower() == "nan":
        return None
    return float(text)


def parse_summary(path):
    classes = {}
    # Example:
    # c5  read.ReadShared.dmt_miss.CompData_DMT      DAT SN->RN      2    7.7e-05
    pat = re.compile(
        r"^c(?P<class>\d+)\s+"
        r"(?P<name>\S+)\s+"
        r"(?P<channel>REQ|RSP|SNP|DAT)\s+"
        r"(?P<dir>\S+)\s+"
        r"(?P<size>\d+)\s+"
        r"(?P<inj>[0-9.eE+-]+)"
    )
    with open(path) as f:
        for line in f:
            m = pat.match(line.strip())
            if not m:
                continue
            c = int(m.group("class"))
            ch = m.group("channel")
            classes[c] = {
                "class": c,
                "name": m.group("name"),
                "channel": ch,
                "subnet": SUBNET[ch],
                "direction": m.group("dir"),
                "size": int(m.group("size")),
                "offered_packet_rate": float(m.group("inj")),
            }
    return classes


def parse_log(path):
    with open(path) as f:
        log = f.read()
    if "====== Overall Traffic Statistics ======" not in log:
        raise RuntimeError("Could not find Overall Traffic Statistics in chi_traffic.log")
    tail = log.split("====== Overall Traffic Statistics ======", 1)[1]
    out = {}
    block_re = re.compile(
        r"====== Traffic class (?P<class>\d+) ======(?P<body>.*?)(?======= Traffic class|Total run time)",
        re.S,
    )
    fields = {
        "packet_latency": r"Packet latency average = ([0-9.eE+-]+|nan)",
        "flit_latency": r"Flit latency average = ([0-9.eE+-]+|nan)",
        "injected_packet_rate": r"Injected packet rate average = ([0-9.eE+-]+)",
        "accepted_packet_rate": r"Accepted packet rate average = ([0-9.eE+-]+)",
        "injected_flit_rate": r"Injected flit rate average = ([0-9.eE+-]+)",
        "accepted_flit_rate": r"Accepted flit rate average = ([0-9.eE+-]+)",
        "hops": r"Hops average = ([0-9.eE+-]+|nan)",
    }
    for m in block_re.finditer(tail):
        c = int(m.group("class"))
        body = m.group("body")
        row = {}
        for key, pat in fields.items():
            mm = re.search(pat, body)
            row[key] = _num(mm.group(1)) if mm else None
        out[c] = row
    return out


def weighted_average(items, value_key, weight_key):
    num = 0.0
    den = 0.0
    for row in items:
        val = row.get(value_key)
        weight = row.get(weight_key)
        if val is None or weight is None or weight <= 0:
            continue
        num += val * weight
        den += weight
    return num / den if den > 0 else None


def aggregate(classes, stats):
    per_class = []
    for c, meta in sorted(classes.items()):
        row = dict(meta)
        row.update(stats.get(c, {}))
        row["offered_flit_rate"] = row["offered_packet_rate"] * row["size"]
        per_class.append(row)

    per_channel = {}
    for ch in CHANNELS:
        rows = [r for r in per_class if r["channel"] == ch]
        offered_flit = sum(r["offered_flit_rate"] for r in rows)
        inj_flit = sum((r.get("injected_flit_rate") or 0.0) for r in rows)
        acc_flit = sum((r.get("accepted_flit_rate") or 0.0) for r in rows)
        inj_pkt = sum((r.get("injected_packet_rate") or 0.0) for r in rows)
        acc_pkt = sum((r.get("accepted_packet_rate") or 0.0) for r in rows)
        per_channel[ch] = {
            "channel": ch,
            "subnet": SUBNET[ch],
            "classes": len(rows),
            "active_classes": sum(1 for r in rows if (r.get("accepted_flit_rate") or 0.0) > 0),
            "offered_flit_rate": offered_flit,
            "injected_flit_rate": inj_flit,
            "accepted_flit_rate": acc_flit,
            "injected_packet_rate": inj_pkt,
            "accepted_packet_rate": acc_pkt,
            "acceptance_ratio": (acc_flit / inj_flit) if inj_flit > 0 else None,
            "packet_latency": weighted_average(rows, "packet_latency", "accepted_packet_rate"),
            "flit_latency": weighted_average(rows, "flit_latency", "accepted_flit_rate"),
            "hops": weighted_average(rows, "hops", "accepted_flit_rate"),
        }
    return per_class, per_channel


def write_csv(per_channel):
    with open(CSV_OUT, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "channel", "subnet", "classes", "active_classes",
            "offered_flit_rate", "injected_flit_rate", "accepted_flit_rate",
            "acceptance_ratio", "packet_latency", "flit_latency", "hops",
        ])
        for ch in CHANNELS:
            r = per_channel[ch]
            w.writerow([
                ch, r["subnet"], r["classes"], r["active_classes"],
                r["offered_flit_rate"], r["injected_flit_rate"], r["accepted_flit_rate"],
                r["acceptance_ratio"], r["packet_latency"], r["flit_latency"], r["hops"],
            ])


def fmt(x, digits=4):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "-"
    return f"{x:.{digits}f}"


def recommendations(per_channel):
    ordered_load = sorted(CHANNELS, key=lambda ch: per_channel[ch]["accepted_flit_rate"], reverse=True)
    ordered_lat = sorted(
        CHANNELS,
        key=lambda ch: per_channel[ch]["flit_latency"] if per_channel[ch]["flit_latency"] is not None else -1,
        reverse=True,
    )
    top_load = ordered_load[0]
    top_lat = ordered_lat[0]
    rec = [
        f"Highest accepted flit throughput is on {top_load} (subnet {per_channel[top_load]['subnet']}).",
        f"Highest weighted flit latency is on {top_lat} (subnet {per_channel[top_lat]['subnet']}).",
        "Keep REQ/RSP/SNP/DAT physically separated; the report shows whether a single channel, rather than protocol coupling, dominates latency.",
        "For the current low-load point, all channels have accepted/injected flit ratio near 1, so this is a baseline latency point rather than saturation.",
    ]
    if per_channel["DAT"]["accepted_flit_rate"] >= per_channel["RSP"]["accepted_flit_rate"]:
        rec.append("If DAT becomes dominant under sweeps, increase DAT bandwidth first: more physical lanes, wider flit, or separate read-data/write-data/DCT data subnets.")
    else:
        rec.append("RSP currently carries comparable or higher packet pressure than DAT; avoid undersizing RSP buffers/allocators even though messages are short.")
    if any((per_channel[ch]["acceptance_ratio"] or 1.0) < 0.95 for ch in CHANNELS):
        rec.append("At least one channel is not draining cleanly; reduce offered load or increase VC/buffer depth on that channel.")
    rec.append("With 2 VC and 2-flit buffers, run a load sweep before final sizing; shallow buffers can sharply reduce the knee point even when this single run drains.")
    return rec


def make_pdf(per_channel):
    rec = recommendations(per_channel)
    with PdfPages(PDF_OUT) as pdf:
        fig = plt.figure(figsize=(8.27, 11.69))
        fig.suptitle("CHI 4-Channel / 4-Subnet Network Analysis", fontsize=15, fontweight="bold", y=0.97)

        x = list(range(len(CHANNELS)))
        labels = [f"{ch}\nsubnet {SUBNET[ch]}" for ch in CHANNELS]

        ax1 = fig.add_axes([0.10, 0.62, 0.82, 0.26])
        acc = [per_channel[ch]["accepted_flit_rate"] for ch in CHANNELS]
        off = [per_channel[ch]["offered_flit_rate"] for ch in CHANNELS]
        width = 0.34
        ax1.bar([i - width/2 for i in x], off, width=width, color="#94a3b8", label="Offered flit rate")
        ax1.bar([i + width/2 for i in x], acc, width=width, color=[COLORS[ch] for ch in CHANNELS], label="Accepted flit rate")
        ax1.set_xticks(x, labels)
        ax1.set_ylabel("flit / node / cycle")
        ax1.set_title("Throughput by channel")
        ax1.grid(axis="y", alpha=0.25)
        ax1.legend()

        ax2 = fig.add_axes([0.10, 0.31, 0.82, 0.22])
        lat = [per_channel[ch]["flit_latency"] or 0 for ch in CHANNELS]
        ax2.bar(x, lat, color=[COLORS[ch] for ch in CHANNELS])
        ax2.set_xticks(x, labels)
        ax2.set_ylabel("cycles")
        ax2.set_title("Weighted flit latency by channel")
        ax2.grid(axis="y", alpha=0.25)

        text = "\n".join(f"- {line}" for line in rec)
        fig.text(0.10, 0.08, text, fontsize=9.5, va="top",
                 bbox=dict(boxstyle="round", fc="#f8fafc", ec="#cbd5e1"))
        fig.text(0.5, 0.035,
                 "Config: 4 subnets (REQ/RSP/SNP/DAT), 2 VCs/input, 2-flit VC buffers, output-first round-robin switch arbitration.",
                 ha="center", fontsize=8.5, color="#475569")
        fig.savefig(PNG_OUT, dpi=120)
        pdf.savefig(fig)
        plt.close(fig)

        fig = plt.figure(figsize=(8.27, 11.69))
        fig.suptitle("Per-Subnet Summary", fontsize=15, fontweight="bold", y=0.97)
        ax = fig.add_axes([0.04, 0.36, 0.92, 0.50])
        ax.axis("off")
        header = ["Channel", "Subnet", "Classes", "Active", "Offered", "Accepted", "Acc/Inj", "Pkt Lat", "Flit Lat", "Hops"]
        rows = []
        for ch in CHANNELS:
            r = per_channel[ch]
            rows.append([
                ch,
                str(r["subnet"]),
                str(r["classes"]),
                str(r["active_classes"]),
                fmt(r["offered_flit_rate"], 5),
                fmt(r["accepted_flit_rate"], 5),
                fmt(r["acceptance_ratio"], 3),
                fmt(r["packet_latency"], 2),
                fmt(r["flit_latency"], 2),
                fmt(r["hops"], 2),
            ])
        table = ax.table(cellText=[header] + rows, loc="center", cellLoc="center")
        table.auto_set_font_size(False)
        table.set_fontsize(9)
        table.scale(1.0, 1.6)
        for col in range(len(header)):
            table[0, col].set_facecolor("#1e293b")
            table[0, col].set_text_props(color="white", fontweight="bold")

        summary = (
            "Interpretation:\n"
            "Accepted flit rate is the channel throughput reported by BookSim after aggregating all classes mapped to the same subnet.\n"
            "Packet/flit latencies are weighted by accepted packet/flit rates, so inactive classes do not skew the channel average.\n"
            "Acceptance ratio close to 1 indicates the run drained at the selected injection point; saturation analysis still requires a load sweep."
        )
        fig.text(0.08, 0.18, summary, fontsize=10, va="top",
                 bbox=dict(boxstyle="round", fc="#fff7ed", ec="#fdba74"))
        pdf.savefig(fig)
        plt.close(fig)


def main():
    classes = parse_summary(SUMMARY)
    stats = parse_log(LOG)
    _, per_channel = aggregate(classes, stats)
    write_csv(per_channel)
    make_pdf(per_channel)
    print(f"Wrote {CSV_OUT}")
    print(f"Wrote {PDF_OUT}")
    print(f"Wrote {PNG_OUT}")
    print("\nChannel summary:")
    for ch in CHANNELS:
        r = per_channel[ch]
        print(
            f"  {ch} subnet {r['subnet']}: "
            f"accepted={fmt(r['accepted_flit_rate'], 6)} flit/node/cyc, "
            f"flit_lat={fmt(r['flit_latency'], 2)} cyc, "
            f"pkt_lat={fmt(r['packet_latency'], 2)} cyc, "
            f"classes={r['classes']} active={r['active_classes']}"
        )


if __name__ == "__main__":
    main()
